---

- name: Change the owner of the tmp dir to root/root and permission to 1777
  action: shell cd /; chmod 1777 tmp

- name: Bring over the autoget agent to /tmp
  action: copy src=rpms/autoget.agent.tar.gz dest=/tmp/autoget.agent.tar.gz

- name: Stop Service - Ignore
  service:
    name: autoget-agent
    state: stopped
  ignore_errors: yes

- name: Install the autoget agent
  action: shell cd /tmp ; tar xvf autoget.agent.tar.gz ; cd autoget.agent ; chmod 755 *.sh ; mkdir /opt/autoget_agent -p ; cp * /opt/autoget_agent/ ; chmod 755 /opt/autoget_agent/main.pl ; chmod 755 /opt/autoget_agent/*.sh ; cp autoget-agent.service /lib/systemd/system/ ; systemctl enable autoget-agent ; systemctl daemon-reload ; systemctl restart autoget-agent ;

- name: Install autoget agent config file into /opt/autoget_agent
  template:
      src: templates/main.pl.j2
      dest: /opt/autoget_agent/main.pl
      owner: root
      group: root
      mode: 0755
  notify: handler_restart_autoget_agentd

- name: Delete the files in /tmp directory
  action: shell cd /tmp ; rm -rf autoget.agent;